### ISSUE TITLE
No "summarize_hierarchies.py" file

### ISSUE THREAD

**Issue by jhrcook** [raphael-group/hierarchical-hotnet#3]
In the README, number 4 of the section describing how to run Hierarchical HotNet states

> 4. Summarize the hierarchies by running the "src/summarize_hierarchies.py" script.

However,  this file does not exist. From what I can tell, the examples provided instead use "src/process_hierarchies.py".

Thank you for developing this tool and putting it open source,
Josh Cook

**Comment by matthewreyna** [comment]
Yes, you are correct, and I updated the README with this correction -- thanks for your help!
